accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    
]

album/urls.py
from django.urls import path
from . import views

app_name = 'album'

urlpatterns = [
    path('showall/', views.showall, name='showall'),
    path('upload/', views.upload, name='upload'),
]

lunchmap/urls.py
from django.urls import path
from . import views

app_name = 'lunchmap'

urlpatterns = [
    path('', views.index, name='index'),
    path('agenda/', views.agenda, name='agenda'),
    path('photolist/',views.photolist, name='photolist'),
    path('photo/',views.photo, name='photo'),
    # path('<int:pk>/', views.DetailView.as_view(), name='bookdetail'),
    path('venue/', views.venue, name='venue'),
    path('restaurant/', views.IndexView.as_view(), name='index02'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('create/', views.CreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
]

# urlpatterns += static(settings.IMAGE_URL, document_root=settings.IMAGE_ROOT)

myapp2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.views.generic import base
from django.conf import settings

urlpatterns = [
    path('lunchmap/', include('lunchmap.urls')),
    path('album/', include('album.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('',  RedirectView.as_view(url='/lunchmap/')),
]+  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

album/models.py
from django.db import models

class Image(models.Model):
    picture = models.ImageField(upload_to='images/')
    comment = models.CharField(max_length=400, null=True)

    def __str__(self):
        return self.comment

lunchmap/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=255)
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Shop(models.Model):
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse ('lunchmap:detail', kwargs={'pk': self.pk })

class Book(models.Model):
    author = models.CharField(max_length=20)
    image = models.ImageField(upload_to='images', blank=True, null=True)
    link = models.CharField(max_length=200)
    title = models.CharField(max_length=32)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

album/forms.py
from django import forms
from .models import Image

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['picture', 'comment']

lunchmap/forms.py
from django import forms
from .models import Book


class BookForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = ('title', 'link','image')

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

album/views.py
from django.shortcuts import render, redirect
from .models import Image
from .forms import ImageForm

def showall(request):
    images = Image.objects.all()
    context = {'images':images}
    return render(request, 'album/showall.html', context)

def upload(request):
    if request.method == "POST":
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('album:showall')
    else:
        form = ImageForm()

    context = {'form':form}
    return render(request, 'album/upload.html', context)

lunchmap/views.py
from django.views import generic
from .models import Category, Shop, Book
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import redirect
from .forms import BookForm
from django.views.generic import RedirectView

def index(request):
    context = {
    }
    return render(request, 'lunchmap/index.html', context)

def agenda(request):
    return render(request, 'lunchmap/agenda.html', context)

def venue(request):
    context = {
    }
    return render(request, 'lunchmap/venue.html', context)

def photolist(request):
    context = {
    }
    return render(request, 'lunchmap/photo_list.html', context)

def photo(request):
    if request.method == "POST":
        form = BookForm(request.POST)
        if form.is_valid():
            book = Book()
            print(request)
            book.title = request.POST['title']
            book.link = request.POST['link']
            book.image = request.FILES['image']
            book.author = request.user
            book.save()
            return redirect('lunchmap: photolist', pk=book.pk)
    else:
        form = BookForm()
        obj = Book.objects.all()

    return render(request, 'lunchmap/photo.html', {
        'form': form,
        'obj': obj
        })

class DetailView(generic.DetailView):
    model = Book

class IndexView(generic.ListView):
    model = Shop

class DetailView(generic.DetailView):
    model = Shop

class CreateView(LoginRequiredMixin, generic.edit.CreateView):
    model = Shop
    fields = ['name', 'address', 'category'] #'__all__'

    def form_valid(self,form):
        form.instance.author = self.request.user
        return super(CreateView, self).form_valid(form)

class UpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    model = Shop
    fields = ['name', 'address', 'category'] #'__all__'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author != self.request.user:
            raise PermissionDenied('You do not have permission to edit.')
        return super(UpdateView, self).dispatch(request, *args, **kwargs)

class DeleteView(LoginRequiredMixin, generic.edit.DeleteView):
    model = Shop
    success_url = reverse_lazy('lunchmap:index')

album/templates/album/showall.html
{% extends 'layout.html' %}
{% block content %}

<h1 class="photo-gallery">Photo Gallery</h1>
<p class="sub-title">当日のピックアップ写真!</p>

{% for image in images %}
    <img src='{{ MEDIA_URL }}{{image.picture}}' width="100%">
    <p>{{ image.comment }}</p>
{% endfor %}

<p><a href="{% url 'album:upload' %}">写真をアップロード</a></p>

{% endblock %}

album/templates/album/upload.html
{% extends 'layout.html' %}
{% block content %}

<h1>Please Upload</h1>

<form enctype="multipart/form-data" action="{% url 'album:upload' %}" method="post">
{% csrf_token %}
{{form.as_p}}
<input type="submit" value="Upload">
</form>

{% endblock %}

lunchmap/templates/lunchmap/agenda.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'&gt;>
        <title>Waikiki Wedding</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/style_layout.css' %}">
        <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/layout.js' %}"></script>
    </head>

    <body>
        <nav class='navbar navbar-expand-sm navbar-dark bg-dark fixed-top'>
            <a class='navbar-brand' href='{% url "lunchmap:index" %}'>Wedding 2020</a>

            <!-- 左側のヘッダー -->
            <ul class='navbar-nav mr-auto'>
              <li class='nav-time menu'>
                <a class="nav-link" href='{% url "lunchmap:agenda" %}'>Agenda</a>
              </li>
              <li class='nav-time menu'>
                <a class="nav-link" href='{% url "lunchmap:venue" %}'>Place</a>
              </li>
              <li class='nav-time menu'>
                <a class="nav-link" href='{% url "lunchmap:photo" %}'>Photos</a>
              </li>
              <li class='nav-time menu'>
                <a class="nav-link" href='{% url "lunchmap:index02" %}'>Restaurant</a>
              </li>
              <li class='nav-time menu'>
                <a class="nav-link" href="#">Blog</a>
              </li>
            </ul>

            <!-- 右側のヘッダー -->
            <ul class='navbar-nav'>
              {% if user.is_authenticated %}
              <li class='nav-time'>
                <span class='navbar-text'>ようこそ {{ user }} さん - </span>
              </li>
              <li class='nav-item'>
                <a href='{% url "logout" %}' class='logout nav-link'>Logout</a>
              </li>
              {% else %}
              <li class='nav-item'>
                <a href='{% url "login" %}' class='login nav-link'>Login</a>
              </li>
              <li class="nav-item">
                <a href='{% url "accounts:signup" %}' class='signup nav-link'> Sign up </a>
              </li>
              {% endif %}
            </ul>
        </nav>

        <div class='container-agenda'>
            <h1 class="agenda-top">Agenda</h1>
            <p>当日の流れは以下の通りとなります</p>

            <ul>
              <li>10時：</li>
              <li>11時：</li>
              <li>12時：挙式</li>
              <li>１３：３０ party開始</li>
              <li>などなど、記載</li>
            </ul>

        </div>
    </body>
</html>

lunchmap/templates/lunchmap/book_detail.html
{% extends 'layout.html' %}
{% block content %}

{% load static %}

  <h1>{{ book.title }}</h1>
  <div>
    <p>{{ book.image.url }}</p>
  </div>

  <div>
    <a href='{% url "lunchmap:photo" %}'>一覧</a>
    <!-- {% if request.user.id == object.author_id %}
      | <a href='{% url "lunchmap:update" shop.pk %}'>編集</a>
      | <a href='{% url "lunchmap:delete" shop.pk %}'>削除</a>
    {% endif %} -->
  </div>

{% endblock %}

lunchmap/templates/lunchmap/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'&gt;>
        <title>Waikiki Wedding</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/style_layout.css' %}">
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
        <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/layout.js' %}"></script>
    </head>

    <body>
      <nav class='navbar navbar-expand-sm navbar-dark fixed-top'>
        <a class='navbar-brand' href='{% url "lunchmap:index" %}'>Waikiki Wedding</a>
        <ul class='navbar-nav mr-auto'>
          <li class='nav-time menu'>
            <a class="nav-link" href='#1'>ご挨拶</a>
          </li>
          <li class='nav-time menu'>
            <a class="nav-link" href='#2'>ウェディング会場</a>
          </li>
          <li class='nav-time menu'>
            <a class="nav-link" href='#3'>当日の過ごし方</a>
          </li>
          <li class='nav-time menu'>
            <a class="nav-link" href='#4'>写真館</a>
          </li>
        </ul>

        <ul class='navbar-nav ml-auto'>
          {% if user.is_authenticated %}
          <li class='nav-time'>
            <span class='navbar-text'>ようこそ {{ user }} さん - </span>
          </li>
          <li class='nav-item'>
            <a href='{% url "logout" %}' class='logout nav-link'>logout</a>
          </li>
          {% else %}
          <li class='nav-item'>
            <a href='{% url "login" %}' class='login nav-link'>Login</a>
          </li>
          <!-- <li class="nav-item">
            <a href='{% url "accounts:signup" %}' class='signup nav-link'> Sign up </a>
          </li> -->
          {% endif %}
        </ul>
      </nav>

        <header>
          <ul>
            <li>
              <a href='{% url "lunchmap:index02" %}'>現地めグルメ</a>
            </li>
            <li>
              <a href='https://weather.yahoo.co.jp/weather/world/US-HI/91182/' target="_blank">ハワイの気候・服装</a>
            </li>
          </ul>
        </header>

        <div class="top-cover">
          <h1>Welcome to our Wedding</h1>
          <p class="name"><span class="sachi">Sachiyo</span> & <span class="sei">Seiichiro</p>

          <div class="countDown">挙式まであと
            <span class="countDownText">
              <script language="JavaScript">
                var now = new Date();
                var point = new Date("2020/03/19");
                var countdown = Math.ceil((point.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
                if (countdown > 0) {
                  document.write(countdown);
                }
              </script>
            </span>日</div>
            <p class="info">2020.03.19</p>
            <p class="info">Aloha Ke Akua, Waikiki</p>
        </div>

        <div class="greeting-wrapper" id="1">
          <div class="category-title">
          <h1 class="title-phrase">Greeting</h1>
          <p class="sub-title">ご挨拶</p>
          </div>

          <div class="greeting">
            <div class="greeting-photo">
              {% load static %}
              <img class="maedori" src="{% static 'lunchmap/images/maedori01.jpg' %}" width="50%" height="50%"></img>
            </div>
            <div class="greeting-text">
              　この度は私たちの結婚を一緒にお祝いいただき<br>誠にありがとうございます。<br><br>
              　無事に入籍し、ハワイの地で無事に挙式を行えるのも<br>皆様の暖かな応援あってのことです。<br><br>
              　当日はぜひ、開放感の溢れるハワイでのパーティを<br>存分にお楽しみください。<br>
                <p>木村誓一郎・幸代</p>
            </div>
          </div>
       </div>

        <div class="category-title" id="2">
        <h1 class="title-phrase">Wedding Place</h1>
        <p class="sub-title">挙式場のご紹介</p>
        </div>

        <div class="place">
          <div class="place-photo">
            {% load static %}
            <img src="{% static 'lunchmap/images/alohake.jpg' %}" width="80%" height="80%"></img>
          </div>
          <div class="place-text">
            <h2>The Private Garden Aloha Ke Akua</h2>
            <h3>ザ・プライベートガーデン アロハ・ケ・アクア</h3>

            <p>雰囲気とコンセプト（＋噂）だけで、新郎新婦とも即決したウェディング会場です。道端アンジェリカなど有名人もこの会場で挙式・パーティを行った模様。
            <br>ワイキキの市街地から車で１時間程度と少し離れますが、自然豊かな環境を独占し、リラックスできること間違いなしです！</p>

            <p>さらに詳細は<a href="https://www.watabe-wedding.co.jp/resort_wedding_overseas/hawaii/chapel_aloha_ke/?utm_source=google&utm_medium=cpc&utm_campaign=rz_br_chapel&utm_content=hawaii_chapel&gclid=CjwKCAiAj-_xBRBjEiwAmRbqYv7Gej1matV3A_kPh5Al7Cbx5Ixhr03G91PCLkk5XDLd0p_oXZE5XhoCr5YQAvD_BwE#" target="_blank">こちら</a>（外部リンク）</p>

          </div>
        </div>

        <!-- <div class="category-title" id="3">
        <h1 class="title-phrase">Agenda</h1>
        <p>ウェディング当日の流れ</p>
        <p>3月19日の挙式当日は、10時半より２箇所のホテルにバスがピックアップに参ります。</p>
        <p>その後は式場へ移動し、挙式・パーティを開催。ワイキキ市街への戻りは<br>16時ごろを予定しておりますので、
          ご予定を調整いただけますと幸いです。</p>
        </div> -->

        <div class="lesson-wrapper" id="3">
          <div class="container">
            <div class="heading">
              <h2>Wedding Day</h2>
              <p class="sub-title">ウェディング当日の流れ</p>
              <p class="text-contents">3月19日の挙式当日の流れは下記の通りとなります。</p>
            </div>
            <div class="lessons">
              <div class="lesson">
                <div class="lesson-icon">
                  <p>集合！（10:35~10:45)</p>
                  <img src="{% static 'lunchmap/images/hilton02.jpg' %}" width="50%" height="50%">
                </div>
                <p class="text-contents">ホテル２箇所へミニバスがピックアップに参ります。<br>10:35 ヒルトンハワイアンビレッジ、<br>10:45 リッツカールトンレジデンシャル<br>にお集まりください。</p>
              </div>
              <div class="lesson">
                <div class="lesson-icon">
                  <p>会場へ移動 (~11:30)</p>
                  <img src="{% static 'lunchmap/images/waikikibus.jpg' %}" width="70%" height="70%">
                </div>
                <p class="text-contents">ミニバスで皆様をウェディング会場へお連れいたします。40分程度の移動時間となりますので、車酔いや暇をしないように酔い止め、スマホ、音楽聴けるもの、話のネタなどなどご持参ください。</p>
              </div>
              <div class="lesson">
                <div class="lesson-icon">
                  <p>挙式・セレモニー (12:00~13:00)</p>
                  <img src="{% static 'lunchmap/images/ceremony.png' %}" width="70%" height="70%">
                </div>
                <p class="text-contents">会場に到着後、皆さん落ち着きましたら早速挙式を行います！挙式とはいえ自然の中でのガーデンウェディングですので、ある程度カジュアルです。格式張らずに、ぜひ笑顔で新郎新婦を迎えてやってください。。</p>
              </div>
              <div class="lesson">
                <div class="lesson-icon">
                  <p>パーティー(13:30~15:30くらい)</p>
                  <img src="{% static 'lunchmap/images/restaurant_space.jpg' %}" width="70%" height="70%">
                </div>
                <p class="text-contents">挙式後、式場内の自然を楽しんでいただきながらパーティー会場へ移動。暖かな緑が広がるパーティ会場で食事やご歓談をお楽しみください。少しばかり参加型のアクティビティもご用意している？……かも。</p>
              </div>
              <div class="clear"></div>
            </div>
          </div>
        </div>

        <div class="photo-wrapper" id="4">
          <div class="container">
            <div class="heading">
              <h2>Photo Gallery</h2>
              <p class="sub-title">新郎新婦とゲストの写真ご紹介</p>
            </div>
            <div class="slide-wrapper">
              <div class="index-btn-wrapper">
                <div class="index-btn">1</div>
                <div class="index-btn">2</div>
                <div class="index-btn">3</div>
                <div class="index-btn">4</div>
              </div>
              <!-- <div class="change-btn-wrapper">
                <div class="change-btn prev-btn">← 前へ</div>
                <div class="change-btn next-btn">次へ →</div>
              </div> -->
              <ul class="slides">
                <li class="slide active"><img src="{% static 'lunchmap/images/maedori03.jpg' %}" width="100%" height="100%"><p>新郎新婦、前撮り＠浜離宮（2020年2月27日）</p></li>
                <li class="slide"><img src="{% static 'lunchmap/images/maedori04.jpg' %}" width="100%" height="100%"><p>新郎新婦、前撮り＠浜離宮（2020年2月27日）</p></li>
                <li class="slide"><img src="{% static 'lunchmap/images/bali.JPG' %}" width="100%" height="100%"><p>新郎新婦、バリ旅行（2019年5月）</p></li>
                {% if user.is_authenticated %}
                <li class="slide"><p>↓↓詳細の閲覧や投稿などにはログインが必要です（画面をクリック）</p><a href='{% url "album:showall" %}' class="toshi"><img src="{% static 'lunchmap/images/toshiandsawa.JPG' %}" width="100%" height="100%"></a><p>新郎の甥と姪（俊和くんと桜和ちゃん）</p></li>
                {% else %}
                <li class="slide"><a href='{% url "login" %}'><img src="{% static 'lunchmap/images/toshiandsawa.JPG' %}" width="100%" height="100%"></a><p>新郎の甥と姪（俊和くんと桜和ちゃん）</p></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>


    <footer>
      <p>お問い合わせ　
      <br>木村誓一郎<br>
        TEL:080-9806-3563</p>
    </footer>

    </body>
</html>

lunchmap/templates/lunchmap/photo_list.html
{% extends 'layout.html' %}
{% block content %}


  <h1 class="restaurant-top">Photo - 写真一覧</h1>
  <table class='table table-striped table-hover'>
      <tr>
        <th>作成者</th><th>写真</th><th>説明</th>
      </tr>

    {% for book in books %}
      <tr>
        <h1><a href='{% url "lunchmap:photo" book.pk %}'>{{ book.title }}</a></h1>
        {{ book.image }}
        {{ book.link }}
      </tr>

    {% endfor %}
  </table>

  {% if user.is_authenticated %}
  <div>
    <a href='{% url "lunchmap:photo" %}'>写真をアップロード</a>
  </div>
  {% endif %}

  {% endblock %}

lunchmap/templates/lunchmap/shop_detail.html
{% extends 'layout.html' %}
{% block content %}

  <h1>{{ shop.name }}</h1>
  <div>
    <p>{{ shop.category.name }}</p>
    <p>{{ shop.address }}</p>
  </div>

  <iframe id='map'
    src='https://www.google.com/maps/embed/v1/place?key=AIzaSyDA7cTXuCisuoTl4DCznOUA-q0w7XEjKuM&q={{ shop.address }}'
    width='100%'
    height='320'
    frameborder='0'>
  </iframe>

  <div>
    <a href='{% url "lunchmap:index02" %}'>一覧</a>
    {% if request.user.id == object.author_id %}
      | <a href='{% url "lunchmap:update" shop.pk %}'>編集</a>
      | <a href='{% url "lunchmap:delete" shop.pk %}'>削除</a>
    {% endif %}
  </div>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'&gt;>
        <title>Waikiki Wedding</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/style_layout.css' %}">
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
        <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/layout.js' %}"></script>
    </head>

    <body>
      <nav class='navbar navbar-expand-sm navbar-dark fixed-top'>
          <a class='navbar-brand' href='{% url "lunchmap:index" %}'>Waikiki Wedding</a>

          <!-- 左側のヘッダー -->
          <!-- <ul class='navbar-nav mr-auto'>
            <li class='nav-time menu'>
              <a class="nav-link" href='#1'>ご挨拶</a>
            </li>
            <li class='nav-time menu'>
              <a class="nav-link" href='#2'>ウェディング会場</a>
            </li>
            <li class='nav-time menu'>
              <a class="nav-link" href='#3'>当日の流れ</a>
            </li>
            <li class='nav-time menu'>
              <a class="nav-link" href='#4'>写真館</a>
            </li>
            <li class='nav-time menu'>
              <a class="nav-link" href='{% url "lunchmap:index02" %}'>Restaurant</a>
            </li>
          </ul> -->

          <!-- 右側のヘッダー -->
          <ul class='navbar-nav'>
            {% if user.is_authenticated %}
            <li class='nav-time'>
              <span class='navbar-text'>ようこそ {{ user }} さん - </span>
            </li>
            <li class='nav-item'>
              <a href='{% url "logout" %}' class='logout nav-link'>Logout</a>
            </li>
            {% else %}
            <li class='nav-item'>
              <a href='{% url "login" %}' class='login nav-link'>Login</a>
            </li>
            <!-- <li class="nav-item">
              <a href='{% url "accounts:signup" %}' class='signup nav-link'> Sign up </a>
            </li> -->
            {% endif %}
          </ul>
      </nav>

    <!-- <body>
        <nav class='navbar navbar-expand-sm navbar-dark bg-dark fixed-top'>
            <a class='navbar-brand' href='{% url "lunchmap:index" %}'>Wedding 2020</a> -->

            <!-- 左側のヘッダー -->
            <!-- <ul class='navbar-nav mr-auto'>
              <li class='nav-time menu'>
                <a class="nav-link" href='{% url "lunchmap:agenda" %}'>Agenda</a>
              </li>
              <li class='nav-time menu'>
                <a class="nav-link" href='{% url "lunchmap:venue" %}'>Place</a>
              </li>
              <li class='nav-time menu'>
                <a class="nav-link" href='{% url "lunchmap:photo" %}'>Photos</a>
              </li>
              <li class='nav-time menu'>
                <a class="nav-link" href='{% url "lunchmap:index02" %}'>Restaurant</a>
              </li>
              <li class='nav-time menu'>
                <a class="nav-link" href="#">Blog</a>
              </li>
            </ul> -->

            <!-- 右側のヘッダー -->
            <!-- <ul class='navbar-nav'>
              {% if user.is_authenticated %}
              <li class='nav-time'>
                <span class='navbar-text'>ようこそ {{ user }} さん - </span>
              </li>
              <li class='nav-item'>
                <a href='{% url "logout" %}' class='logout nav-link'>Logout</a>
              </li>
              {% else %}
              <li class='nav-item'>
                <a href='{% url "login" %}' class='login nav-link'>Login</a>
              </li>
              <li class="nav-item">
                <a href='{% url "accounts:signup" %}' class='signup nav-link'> Sign up </a>
              </li>
              {% endif %}
            </ul>
        </nav> -->

        <div class='container'>
            {% block content %}
            {% endblock %}
        </div>

        <p class="go-to-top"><a href="{% url 'lunchmap:index' %}">トップに戻る</a></p>
    <footer>
      <p>お問い合わせ　
      <br>木村誓一郎<br>
        TEL:080-9806-3563</p>
    </footer>
    </body>
</html>